config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
    end
  end

end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, :weight, :width, :height, :depth, :sku, :supplier_id, presence: true
  validates :name, :sku, uniqueness: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action(:set_product_model, only: [:show, :edit, :update])
  before_action(:authenticate_user!, only: [:index])

  def index
    @product_models = ProductModel.all
  end

  def show; end

  def new
    @product_model = ProductModel.new()
    @suppliers = Supplier.all
  end

  def create
    @product_model = ProductModel.new(product_model_params())

    if @product_model.save
      flash[:notice] = 'Modelo de Produto cadastrado com sucesso!'
      redirect_to(@product_model)
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Modelo de Produto não cadastrado.'
      return render('new')
    end
  end

  def edit
    @suppliers = Supplier.all
  end

  def update
    if @product_model.update(product_model_params())
      flash[:notice] = 'Modelo de Produto atualizado com sucesso!'
      redirect_to(@product_model)
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Modelo de Produto não pôde ser atualizado.'
      return render('edit')
    end
  end

  private

  def set_product_model()
    @product_model = ProductModel.find(params[:id])
  end

  def product_model_params
    params.require(:product_model).permit(:name, :weight, :width, :height, :depth, :sku, :supplier_id)
  end
end

app/views/product_models/_form.html.erb
<%= form_with model: @product_model do |form| %> 
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :width %>
    <%= form.number_field :width %>
  </div>

  <div>
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div>
    <%= form.label :depth %>
    <%= form.number_field :depth %>
  </div>

  <div>
    <%= form.label :sku %>
    <%= form.text_field :sku %>
  </div>

  <div>
    <%= form.label :supplier_id %>
    <%= form.collection_select(:supplier_id, @suppliers, :id, :brand_name) %>
  </div>

  <div>
    <%= form.submit 'Enviar' %>
  </div>
<% end %>

app/views/product_models/edit.html.erb
<h1>Editar modelo de produto</h1>

<% if @product_model.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
  <% @product_model.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= render('form') %>

<%= link_to 'Cancelar', @product_model %>

app/views/product_models/index.html.erb
<%= link_to 'Cadastrar Modelo de Produto', new_product_model_path %>

<% if @product_models.any? %>
  <% @product_models.each do |product_model|%>
    <h3><%= link_to product_model.name, product_model %></h3>

    <ul>
      <li><p>SKU: <%= product_model.sku %></p></li>
      <li><p>Fornecedor: <%= product_model.supplier.brand_name %></p></li>
    </ul>
  <% end %>
<% else %>
  <p>Não existem modelos de produtos cadastrados.</p>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/product_models/new.html.erb
<h2>Cadastrando um novo modelo de produto</h2>

<% if @product_model.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
  <% @product_model.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= render('form') %>

<%= link_to 'Cancelar', product_models_path %>

app/views/product_models/show.html.erb
<h2>Modelo de Produto: <%= @product_model.name %></h2>

<ul>
  <li><p>Fornecedor: <%= @product_model.supplier.brand_name %></p></li>
  <li><p>Cidade: <%= @product_model.width %> x <%= @product_model.height %> x <%= @product_model.depth %></p></li>
  <li><p>SKU: <%= @product_model.sku %></p></li>
  <li><p>Peso: <%= @product_model.weight %></p></li>
</ul>

<%= link_to('Editar', edit_product_model_path(@product_model)) %>
<%= link_to('Voltar', product_models_path) %>