config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  has_many :order_items
  has_many :product_models, through: :order_items

  enum status: { pending: 0, delivered: 5, canceled: 9 }

  validates :code, :estimated_delivery_date, presence: true

  #para ser valido
  validate :estimated_delivery_date_is_future

  #antes de conferir a validação
  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(10)
  end

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date != nil && self.estimated_delivery_date <= Date.today
      self.errors.add(:estimated_delivery_date, ' deve ser maior que hoje')
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action(:authenticate_user!)
  before_action(:set_order_and_check_user, only: [:show, :edit, :update, :destroy, :delivered, :canceled])

  def index
    # <% @user_orders.each do |order|%> # NO INDEX DA PARA COLOCAR ASSIM, VER MELHOR DEPOIS
    @orders = current_user.orders
  end

  def show

  end

  def new
    @order = Order.new
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save
      flash[:notice] = 'Pedido registrado com sucesso'
      redirect_to(@order)
    else
      @warehouses = Warehouse.all
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível registrar o pedido'
      render('new')
    end
  end

  def edit
    @warehouses = Warehouse.all
    @suppliers = Supplier.all
  end

  def update
    if @order.update(order_params)
      flash[:notice] = 'Pedido atualizado com sucesso'
      redirect_to(@order)
    else
      flash.now[:notice] = 'Pedido não pôde ser atualizado'
      return render('edit')
    end
  end

  def destroy
    @order.destroy
    flash[:notice] = 'Pedido removido com sucesso'
    redirect_to(orders_path)
  end

  def search
    @code = params[:query]
    @orders = Order.where("code LIKE ?", "%#{@code}%")
  end

  def delivered
    @order.delivered!
    @order.order_items.each do |item|
      item.quantity.times do
        StockProduct.create!(
          order: @order,
          product_model: item.product_model,
          warehouse: @order.warehouse
        )
      end
    end
    redirect_to @order
  end

  def canceled
    @order.canceled!
    redirect_to @order
  end

  private

  def set_order_and_check_user
    @order = Order.find(params[:id])
    if @order.user != current_user
      return redirect_to root_path, notice: 'Voce nao pode acessar pedido de outros usuários'
    end
  end

  def order_params
    params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: @order) do |form| %>
  <div>
    <%= form.label :warehouse_id %>
    <%= form.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>

  <div>
    <%= form.label :supplier_id %>
    <%= form.collection_select :supplier_id, @suppliers, :id, :corporate_name %>
  </div>

  <div>
    <%= form.label :estimated_delivery_date %>
    <%= form.date_field :estimated_delivery_date %>
  </div>
  <br>
  <%= form.submit 'Gravar' %>
  <br><br>
  <%= link_to 'Cancelar', root_path %>
<% end %>

app/views/orders/_order.html.erb
<h3><%= link_to "Pedido: #{order.code}", order %></h3>
<ul>
  <li><%= Order.human_attribute_name(:status) %>: <%= t(order.status) %></li>
  <li><%= Order.human_attribute_name(:user_id) %>: <%= order.user.description %></li>
  <li><%= Order.human_attribute_name(:warehouse_id) %>: <%= order.warehouse.full_description %></li>
  <li><%= Order.human_attribute_name(:supplier_id) %>: <%= order.supplier.corporate_name %></li>
  <li><%= Order.human_attribute_name(:estimated_delivery_date) %>: <%= I18n.localize(order.estimated_delivery_date) %></li>

  <%= link_to 'Editar', edit_order_path(order) %>
</ul>

app/views/orders/edit.html.erb
<h1>Editar pedido</h1>

<% if @order.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
  <% @order.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= render('form') %>

app/views/orders/index.html.erb
<% @orders.each do |order|%>
  <%= render order %>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/orders/new.html.erb
<h1>Registrar pedido</h1>

<% if @order.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
  <% @order.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= render('form') %>

app/views/orders/search.html.erb
<h1>Resultados da Busca por: <%= @code %></h1>

<% if @orders.any? %>
  <p><%= @orders.count %> <%= Order.model_name.human(count: @orders.count) %> <%= t(:found, count: @orders.count) %></p>
  <% @orders.each do |order| %>
    <%= render order %>
  <% end %>
<% else  %>
  <p>Nenhum pedido encontrado</p>
<% end %>

app/views/orders/show.html.erb
<h1><%= Order.model_name.human %>: <%= @order.code %></h1>

<p><%= Order.human_attribute_name(:user_id) %>: <%= @order.user.description %></p>
<p><%= Order.human_attribute_name(:warehouse_id) %>: <%= @order.warehouse.full_description %></p>
<p><%= Order.human_attribute_name(:supplier_id) %>: <%= @order.supplier.corporate_name %></p>
<p><%= Order.human_attribute_name(:estimated_delivery_date) %>: <%= I18n.localize(@order.estimated_delivery_date) %></p>
<p><%= Order.human_attribute_name(:status) %>: <%= t(@order.status) %></p>

<h3>Itens do Pedido</h3>
<%= link_to 'Adicionar Item', new_order_order_item_path(order_id: @order.id) %>
<% @order.order_items.each do |item| %>
  <p><%= item.quantity %> x <%= item.product_model.name %> </p>
<% end %>

<% if @order.pending? %>
  <%= button_to 'Entregue', delivered_order_path(@order.id) %> <br>
  <%= button_to 'Cancelar', canceled_order_path(@order.id) %> <br>
<% end %>

<%= link_to 'Editar', edit_order_path(@order.id) %><br>
<%= link_to 'Voltar', orders_path %>