config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
    end
  end

end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models

  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence: true
  validates :brand_name, :registration_number, :email, uniqueness: true
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action(:set_supplier, only: [:show, :edit, :update])

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new()
  end

  def create
    @supplier = Supplier.new(supplier_params())

    if @supplier.save
      flash[:notice] = 'Fornecedor cadastrado com sucesso!'
      redirect_to(@supplier)
    else
      flash.now[:notice] = 'Fornecedor não cadastrado.'
      return render('new')
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params())
      flash[:notice] = 'Fornecedor atualizado com sucesso!'
      redirect_to(@supplier)
    else
      flash.now[:notice] = 'Fornecedor não pôde ser atualizado.'
      return render('edit')
    end
  end

  private

  def set_supplier()
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email)
  end
end

app/views/suppliers/_form.html.erb
<%= form_with model: @supplier do |form| %> 
  <div>
    <%= form.label :corporate_name %>
    <%= form.text_field :corporate_name %>
  </div>

  <div>
    <%= form.label :brand_name %>
    <%= form.text_field :brand_name %>
  </div>

  <div>
    <%= form.label :registration_number %>
    <%= form.number_field :registration_number %>
  </div>

  <div>
    <%= form.label :full_address %>
    <%= form.text_field :full_address %>
  </div>

  <div>
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit 'Enviar' %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar fornecedor</h1>

<% if @supplier.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
  <% @supplier.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= render('form') %>

<%= link_to 'Cancelar', @supplier %>

app/views/suppliers/index.html.erb
<%= link_to 'Cadastrar Fornecedor', new_supplier_path %>

<% if @suppliers.any? %>
  <% @suppliers.each do |supplier|%>
    <h3><%= link_to supplier.brand_name, supplier %></h3>

    <ul>
      <li><p>Endereço: <%= supplier.city %> - <%= supplier.state %></p></li>
    </ul>
  <% end %>
<% else %>
  <p>Não existem fornecedores cadastrados.</p>
<% end %>

<%= link_to 'Voltar', root_path %>

app/views/suppliers/new.html.erb
<h2>Cadastrando um novo galpão</h2>

<% if @supplier.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  <ul>
  <% @supplier.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= render('form') %>

<%= link_to 'Cancelar', suppliers_path %>

app/views/suppliers/show.html.erb
<h2>Fornecedor: <%= @supplier.brand_name %></h2>

<h3><%= @supplier.corporate_name %></h3>

<ul>
  <li><p>Nome: <%= @supplier.registration_number %></p></li>
  <li><p>Cidade: <%= @supplier.full_address %></p></li>
  <li><p>Área: <%= @supplier.city %></p></li>
  <li><p>Endereço: <%= @supplier.state %></p></li>
  <li><p>CEP: <%= @supplier.email %></p></li>
</ul>

<%= link_to('Editar', edit_supplier_path(@supplier)) %>
<%= link_to('Voltar', suppliers_path) %>