config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create, :edit, :update]

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
  </head>
  <body>
    <header>
      <%= link_to root_path do %>
        <h1>Galpões & Estoque</h1>
      <% end %>
      <nav style="font-size: 1.2rem; display: flex; gap: 0.5rem;">
        <%= link_to 'Galpões', root_path %> |
        <%= link_to 'Fornecedores', suppliers_path %> |
        <%= link_to 'Modelos de Produtos', product_models_path %> |
        <% if user_signed_in? %>
          <% if @user_orders.any? %>
            <%= link_to 'Listar Pedidos', orders_path %> |
            <%= link_to 'Registrar Pedido', new_order_path %> |
          <% else %>
            <%= link_to 'Registrar Pedido', new_order_path %> |
          <% end %>
          <%= current_user.name %> |
          <%= form_with(url: search_orders_path, method: :get) do |form| %>
            <%= form.label :query, 'Buscar Pedido' %>
            <%= form.text_field :query %>
            <%= form.submit 'Buscar' %>
          <% end %>
          |<%= button_to 'Sair', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Registrar Pedido', new_order_path %> |
          <%= link_to 'Entrar', new_user_session_path %>
        <% end %>
      </nav>
    </header>
    <main>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
      <%= yield %>
    </main>
  </body>
</html>